# SwiftLint configuration file

# Rules to disable
disabled_rules:
  - trailing_whitespace
  - line_length

# Rules to enable
opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional

# Paths to include/exclude
included:
  - MyCICDApp

excluded:
  - Carthage
  - Pods
  - build
  - DerivedData

# Rule configurations
line_length:
  warning: 120
  error: 200

identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 40
    error: 60

type_name:
  min_length: 3
  max_length: 40

function_body_length:
  warning: 50
  error: 100

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20
